production:
  auto_deploy_on: refs/heads/master
  deployments:
  - environment: production
    production_environment: true
    url: https://deliverybot.web.app

    payload:
      steps:
      - name: gcr.io/deliverybot/cloud-functions
      name: deliverybot
      project: deliverybot
      region: us-central1
      runtime: nodejs8
      entrypoint: deliverybot
      source: gs://deliverybot-cache/deliverybot-{{short_sha}}.zip

    required_contexts:
    - "Build (538437845459)"
