steps:
  - name: "gcr.io/$PROJECT_ID/restore_cache"
    id: "cache"
    args:
    - "--bucket=gs://$PROJECT_ID-cache/"
    - "--key=node_modules"
  - name: "gcr.io/cloud-builders/npm:node-10.10.0"
    id: "install"
    args: ["install"]
    waitFor: ["cache"]
  - name: "gcr.io/cloud-builders/npm:node-10.10.0"
    id: "test"
    args: ["test"]
    waitFor: ["install"]
  - name: "gcr.io/$PROJECT_ID/save_cache"
    id: "save"
    waitFor: ["install"]
    args:
    - "--bucket=gs://$PROJECT_ID-cache/"
    - "--key=node_modules"
    - "--path=node_modules"
